# Generated by Django 5.1.7 on 2025-05-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_cart_id_alter_enrolledcourse_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='cart_id',
            new_name='oid',
        ),
    ]
