# Generated by Django 5.1.7 on 2025-05-18 14:48

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_variantitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='variant_item_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=20, prefix=''),
        ),
    ]
